3.5.7

diff --git a/templates/console-analysisnode-statefulset-deployment.yaml b/templates/console-analysisnode-statefulset-deployment.yaml
--- a/templates/console-analysisnode-statefulset-deployment.yaml
+++ b/templates/console-analysisnode-statefulset-deployment.yaml
@@ -62,7 +62,7 @@ spec:
           type: RuntimeDefault
 {{- end }}
       initContainers:     
-{{- if .Values.RestrictedSecurityMode }}    
+{{- if or .Values.RestrictedSecurityMode .Values.prepareMigrationToAnalysisNodeFS }}
         - name: init-folders
           image: "{{.Values.ConsoleAnalysisNodeImage.name}}:{{.Values.ConsoleAnalysisNodeImage.tag}}"
           imagePullPolicy: "{{.Values.ConsoleAnalysisNodeImage.pullPolicy}}"
@@ -70,11 +70,36 @@ spec:
           - /bin/bash
           - -c
           - |
+  {{- if .Values.RestrictedSecurityMode }}
             rm -rf /carl-volume/*
             cp -r /home/carl/* /carl-volume/ || true
+  {{- end }}
+  {{- if .Values.prepareMigrationToAnalysisNodeFS }}
+            set -e
+            echo Starting migration to FS...
+            echo Check if required folders exist in source...
+            for dir in common-data delivery deploy; do
+              if [ ! -d "{{ .Values.anadir.datadirmount }}-mig/$dir" ]; then
+                echo  "ERROR: Required folder '$dir' is missing from source!"
+                exit 1
+              fi
+            done
+            echo Copying...
+            # cp -af {{ .Values.anadir.datadirmount }}-mig/. {{ .Values.anadir.datadirmount }}/
+            cd {{ .Values.anadir.datadirmount }}-mig && tar cf - --exclude='./lost+found' . | tar xf - -C {{ .Values.anadir.datadirmount }}/ --no-overwrite-dir
+            echo Done.
+  {{- end }}
           volumeMounts:
+  {{- if .Values.RestrictedSecurityMode }}
             - name: carl-dir
               mountPath: /carl-volume
+  {{- end }}
+  {{- if .Values.prepareMigrationToAnalysisNodeFS }}
+            - mountPath: {{ .Values.anadir.datadirmount }}
+              name: shared-datadir
+            - mountPath: {{ .Values.anadir.datadirmount }}-mig
+              name: shared-datadir-mig
+  {{- end }}
           securityContext:
             readOnlyRootFilesystem: true
             runAsUser: 10001
@@ -198,6 +223,8 @@ spec:
 {{- if .Values.EnablePostgresSSL }}
             - name: CASTCONNECTIONEXTRAPARAMETERS
               value: /etc/ssl/certs-postgres/sslconfig.ini
+            - name: NB_OF_THREADS_FOR_NODE 
+              value: {{ .Values.MaxParallelAnalysisPerNode }}
 {{- end }}
           image: "{{ .Values.ConsoleAnalysisNodeImage.name }}:{{ .Values.ConsoleAnalysisNodeImage.tag}}"
           imagePullPolicy: "{{ .Values.ConsoleAnalysisNodeImage.pullPolicy }}"
@@ -269,6 +296,11 @@ spec:
           emptyDir: {}
         - name: run
           emptyDir: {}
+{{- end }}
+{{- if .Values.prepareMigrationToAnalysisNodeFS }}
+        - name: shared-datadir-mig
+          persistentVolumeClaim:
+            claimName: pvc-shared-datadir-mig
 {{- end }}
         - name: shared-datadir
           persistentVolumeClaim:
